### ISSUE TITLE
怎么进去呢，大神，翻墙也不行

### ISSUE THREAD

**Issue by unbeau** [ckjbug/Hacking#2]

**Comment by dqwyy** [comment]
Have you downloaded [Tor browser](https://www.torproject.org/projects/torbrowser.html)? `.onion` domains can must be browser through Tor browser.

**Comment by dqwyy** [comment]
Use [Tor browser](https://www.torproject.org/projects/torbrowser.html) to browse `.onion` sites.

**Comment by pengliheng** [comment]
建议看[教程](https://github.com/pengliheng/pengliheng.github.io/issues/61)，首先你要有自己的国外vpn，这样快很多。
