### ISSUE TITLE
Phishing site!!!!

### ISSUE THREAD

**Issue by anti-scam-human** [ckjbug/Hacking#9]
There is a dangerous site in the readme, the deeponionweb.com, they occasionally show phishing urls, heres proof: https://web.archive.org/web/20190511144749/https://deeponionweb.com/Dream-Market-Alternative-Links/

If You hover over the links You can see so instead of '.onion', they're '.onion.id'

Please dont give scammers backlinks

As well as this sites content is a ripoff of another site which is now offline

**Comment by ckjbug** [comment]
thinks，i will update as soon as possible.
